let alien_colour : string = "yellow" ;

if (alien_colour == 'green')
{
    console.log("player just earned 5 points");
} 

else if (alien_colour == "red") 
{
    console.log("player just earned 15 points");
}

else {
    console.log("player just earned 10 points");
}


alien_colour = "green";


if (alien_colour == 'green') {
    console.log("player just earned 5 points");
} 

else if (alien_colour == "red") 
{
        console.log("player just earned 15 points");
}

else {
    console.log("player just earned 10 points");
}


alien_colour = "red";


if (alien_colour == 'green') {
    console.log("player just earned 5 points");
} 

else if (alien_colour == "red") 
{
        console.log("player just earned 15 points");
}

else {
    console.log("player just earned 10 points");
}


